
services:
  postgres:
    image: postgres:17
    ports:
      - "5512:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tripmaxxer
    volumes:
      - ./data:/var/lib/postgresql/data
